### ISSUE TITLE
[TODO] Table widget

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#857]
- [x] Column definition: readOnly
- [x] Column type: autocomplete (modules\backend\assets\js\october.autocomplete.js)
- [ ] Column type: number (http://tinyurl.com/lll2bus)
- [x] Create "DataTable" Form widget
- [x] Custom buttons in toolbar
- [ ] Fields turn red with invalid data (see "number" column type)
- [ ] Search table data
- [x] Server side data source
- [x] Validation options similar to Component Property validation
- [ ] Form widget only submits when handler is called `onSave`, we need to add a feature to pass the data with every request, i.e. `postbackHandlerName` option can be `null` (allow all)

**Comment by serialscoper101** [comment]
It would be useful to be able to add links inside table cells in the table. It is really annoying doing it for large tables of links like [this one](http://www.mhscompsci.com/courses/ap-compsci) where you have to write out the twig linking separately.  I made the table with normal links and then used a complex regex to search and replace the links but I think there is a better way. Maybe allow for drag and drop from the assets menu on the left and it would auto link with the twig filters or autocomplete the file names when linking it? Anyways these are just some things that could add to the table widget.  Loving the framework so far!

**Comment by jonpxpx** [comment]
Would be great if we could add options to a data table dropdown without it being an auto relation... Currently trying to sort a table dropdown (author - firstname, lastname) and unable to pass it options within a pivot definition. Unless I am missing something? listAuthors resides within my Pivots model file.

```
author:
    title: Author
    type: dropdown
    options: listAuthors
```

**Comment by jonpxpx** [comment]
Update on this, it seems that my changes were being reflected on checking the response, however the way the dropdown is built up, it is actually built using a for loop and therefore places the dropdown options in the order of 1,2,3 instead of the results order.

**Comment by jonpxpx** [comment]
@daftspunk Model returns the correct order, looks like the JS then orders by the key, what do you think the best approach is for this?
