### ISSUE TITLE
[TODO] Website / General

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#858]
#### Stable
- Tag builds in repo from stable onward
- [x] Upgrade to 5.1 LTS
- [ ] Discovery for sortable plugin
- [x] Complete table API, allow widgets to have their own classes #857
- [x] Layout experiment / Refresh UI
- [x] Dedicated hostname for API

#### DB
- [ ] Nullable columns by default
- [ ] Better index name generation (use acronym for shorter)
- [ ] See if model can auto generate table name using author / plugin from namespace

#### Major

- [ ] Customize back-end nav
- [ ] Dashboard presets #1131
- [ ] Make guided tour
- [x] Add changelog to core updates

#### Possible breaking changes
- [x] Strip out "if year >" deprecations
- [ ] Remove the eval() from framework.js:361
- [ ] The RelationController::relationExtendQuery method should be removed when scopes are respected - a relation scope is an extension of the query #1203 
- [ ] Media Manager handler "onDelete" is too vague

#### Features

- [ ] Plugins should download dependencies #36
- [x] Content object with MD type is parsing content every time, even for listing the objects in the back-end CMS area
- [ ] Improve formatting on Event Log stack trace #910 
- [ ] Find a way to make the List collection available to the page (counting records, etc)
- [ ] Consider respecting Laravel's decision for trans() to return Lang object
- [ ] Investigate translate support for repeater widget https://github.com/rainlab/translate-plugin/issues/54
- [ ] Add `recordUrl` support to Record Viewer to link the user to another page, if necessary
- [ ] Add creation ability to Relation form widget -- *Create new* in the dropdown/checkbox list
- [ ] Add support to define Redactor buttons in Richeditor form field definition #636
- [ ] Allow timezone to be set by the user #748
- [ ] Modules should load before Plugins - find a way to inverse this for routes.php
- [ ] Compile brand settings / combine assets to real files (config option)
- [ ] Pass language strings to Media Manager
- [ ] Need a "no cache at all" options for recompiling LESS,etc
- [x] Dashboard widgets should defer their data requesting using AJAX so they don't kill/lag the whole page request
- [ ] Address the CSRF concerns https://github.com/octobercms/library/issues/105
- [ ] Customize other users preferences (locale, timezone, back-end nav)
- [ ] Implement native SCSS compiler
- [ ] Improve `{{ dump() }}` to output vars like `dd()`
- [ ] Use `@alias` for soft component implementation
- [ ] Add `image` list column type
- [ ] Add to backend: "Your last login was on.... [date]"
- [ ] Add timeout to backend "Are you still there, [name]? Enter Password: [    ]"
- [ ] Improve back-end update UI to collapse notes a la iOS
- [ ] Add `filter` option to relation and recordfinder to specify a scope. Find an equivalent for RelationController.

#### Bugs

- [ ] Investigate duplicate moment.js and webfont assets in Backend
- [ ] Setting the menu context is case sensitive, it shouldn't be
- [ ] fileinfo extension is a requirement #1046
- [ ] ColorPicker zindex is broken in modals #992
- [ ] Ensure `disabled.json` has writable permissions
- [ ] Markdown editor in a popup
- [x] Load the dash using AJAX (critical errors result in admin lockout)
- [ ] Super users are unable to modify their own group assignments
- [ ] `CodeParser` class should use `\Cache` class instead of filesystem

#### Website

- [ ] API Documentation (Refs: https://github.com/octobercms/docs/pull/78)
- [ ] Forum users should have a better avatar (Supply it from the forum plugin)
- [ ] Users can delete projects #167
- [ ] Detect requirements from plugins in Plugin.php
- [x] Move the plugins Support forum to its own page, move link to side bar
- [ ] Support "Table of Contents" for docs
- [ ] Notice about Support section on social media pages
- [ ] The author interface: change the color of draft to something else other than green

#### Maybes
- [ ] Add slug to User model
- [ ] Add relation support to repeater widget
- [ ] Separate the vendor package to its own archive (MAX EXEC TIME FIX)
- [ ] Demo theme should have a customization field for "backend URL" automatically set by the demo
- [ ] Add repair utility to the installer
- [ ] Composer install should enabled `cms.disableCoreUpdates`
- [ ] Add "auto sizing" to FileUpload form widget (if height/width is omitted, calculate automatically)
- [ ] Build the Context Help System #3 
- [ ] [Website] Add the option to sign in with Github
- [ ] [Website] Create Definition / Examples tabs in docs
- [ ] [Website] Update [lightbox](http://blueimp.github.io/Bootstrap-Image-Gallery/) for plugin screenshots 
- [ ] Make core manager classes use IoC singleton pattern (IoC all the things!)
- [ ] Release Ng Blog theme

#### Complete
- [x] Using trigger api in a popup destroys the modal overlay
- [x] Move plugin and theme browser in to core
- [x] Add docs about `APP_ENV` set up #1015 
- [x] Installer should simply ask for a starter theme
- [x] Themes download dependencies
- [x] Create driver plugin(s) - October.[Cloud|Mail|Queue]Drivers
- [x] Release a theme implementing Blog + Forum (dependencies automatically download)
- [x] Templating / Markup Guide
- [x] CMS + Static Pages Controllers to support AJAX
- [x] Detect requirements from themes in theme.yaml
- [x] Core test build should be pulled from `develop` branch
- [x] Build should update October\Rain from github, not rely on packagist
- [x] Strip out `///` in URLs to reduce content duplication #665
- [x] Force redirect to HTTPS when policy is strict
- [x] Force redirect if trailing slash #634 #1023
- [x] Add `previewMode` support to Record Viewer and File Upload
- [x] Improve permissions UI #345
- [x] Add `|media` filter
- [x] Major version upgrades for Plugins #785
- [x] Back-end UI Guide
- [x] Pull plugin test suite in to core - see https://github.com/rainlab/translate-plugin/pull/83
- [x] Extension package is allowing protected properties and methods to be accessed
- [x] Form controller should exclude values not defined in fields.yaml
- [x] Recreate a users auth key when they log out, forcing all others to be logged out
- [x] Add groups to Users
- [x] Create a Markdown form widget #379 #635

**Comment by Teranode** [comment]
why is relation to repeater in the "maybes" isnt it suppose to repeat information like relations and dropdowns and such?
