### ISSUE TITLE
[TODO] OctoberCMS Screencasts

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#859]
- [x] [Introduction to October](https://vimeo.com/79963873)
- [x] [Blog / Forum Website](https://vimeo.com/97088926)
- [x] [Translating Content](https://vimeo.com/102449697)
- [x] [Extending User plugin](https://vimeo.com/108040919)
- [x] [Mastering Components](https://vimeo.com/104896353)
- [x] [Backend Relations](https://vimeo.com/123489421)
- [x] [Media Manager](https://vimeo.com/125763187)
- [x] Static Pages
